Improve error reporting and allow compilation with Linux versions > 3.0

diff --git a/sh/_guess-host-architecture-and-os b/sh/_guess-host-architecture-and-os
--- a/sh/_guess-host-architecture-and-os
+++ b/sh/_guess-host-architecture-and-os
@@ -3,28 +3,37 @@
 # _guess-host-architecture-and-os  -- guess architecture and system info
 #
 
+fail() {
+    echo "Error: $*" >&2
+    exit 1
+}
+
 export PATH
 PATH="/bin:/usr/bin"
 
-case `uname -s` in
+uname_s="`uname -s`"
+case "$uname_s" in
   SunOS)
-    case `uname -r` in
+    uname_r="`uname -r`"
+    case "$uname_r" in
       4.*)
 	OS=sunos
-	case `/usr/bin/arch` in
+	arch="`/usr/bin/arch`"
+	case "$arch" in
 	  sun4) ARCHITECTURE=sparc32;;
-	  *) exit 1;;
+	  *) fail "Unhandled $uname_s $uname_r architecture: $arch" ;;
 	esac
       ;;
       5.*)
 	OS=solaris
-	case `uname -p` in
+	uname_p="`uname -p`"
+	case "$uname_p" in
 	  sparc) ARCHITECTURE=sparc32;;
 	  *86) ARCHITECTURE=intel32;;
-	  *) exit 1;;
+	  *) fail "Unhandled $uname_s $uname_r architecture: $uname_p" ;;
 	esac
       ;;
-      *) exit 1;;
+      *) fail "Unhandled $uname_s architecture: $uname_r" ;;
     esac
     ;;
   AIX)
@@ -32,69 +41,78 @@ case `uname -s` in
     ARCHITECTURE=pwrpc32
     ;;
   Darwin)
-    case `uname -p` in
+    uname_p="`uname -p`"
+    case "$uname_p" in
       powerpc)
 	ARCHITECTURE=pwrpc32
-	case `uname -r` in
+	uname_r="`uname -r`"
+	case "$uname_r" in
 	  5*) OS=darwin5; ;; # MacOS X 10.1
 	  6*) OS=darwin;  ;; # MacOS X 10.2
 	  7*) OS=darwin;  ;; # MacOS X 10.3
 	  8*) OS=darwin;  ;; # MacOS X 10.4
-	*) exit 1;;
+	  *) fail "Unhandled $uname_s $uname_p version: $uname_r" ;;
 	esac;;
       i386) ARCHITECTURE=intel32; OS=darwin;; # MacOS X 10.4+
     esac
     ;;
   Linux)
     OS=linux
-    case `uname -m` in
+    uname_m="`uname -m`"
+    case "$uname_m" in
       *86)
 	ARCHITECTURE=intel32
-      # we no longer support Linux before the 2.2 kernel.
-	case `uname -r` in
+        # we no longer support Linux before the 2.2 kernel.
+	uname_r="`uname -r`"
+	case "$uname_r" in
 	  2.2.*) ;;
 	  2.3.*) ;;
 	  2.4.*) ;;
 	  2.5.*) ;;
 	  2.6.*) ;;
-	  3.0.*) ;;
-	  *) exit 1 ;;
+	  3.*) ;;
+	  *) fail "Unhandled $uname_s $uname_m version: $uname_r" ;;
 	esac
 	;;
       x86_64) ARCHITECTURE=intel64;;
       pwrpc32)
 	ARCHITECTURE=pwrpc32
-	case `uname -r` in
+	uname_r="`uname -r`"
+	case "$uname_r" in
 	  *osfmach*) OS=mklinux ;;
-	  *) ;;
+	  *) fail "Unhandled $uname_s $uname_m version: $uname_r" ;;
 	esac
 	;;
-      *) exit 1;;
+      *) fail "Unhandled $uname_s machine architecture: $uname_m" ;;
     esac
     ;;
   FreeBSD)
     OS=freebsd
-    case `uname -m` in
+    uname_m="`uname -m`"
+    case "$uname_m" in
       *86) ARCHITECTURE=intel32;;
-      *) exit 1;;
+      *) fail "Unhandled $uname_s machine architecture: $uname_m" ;;
     esac
     ;;
   NetBSD)
-    case `uname -r` in
+    uname_r="`uname -r`"
+    case "$uname_r" in
       2*) OS=netbsd2;;
       3*) OS=netbsd;;
-      *) exit 1;;
+      *) fail "Unhandled $uname_s version: $uname_r" ;;
     esac
-    case `uname -m` in
+    uname_m="`uname -m`"
+    case "$uname_m" in
       *86) ARCHITECTURE=intel32;;
-      *) exit 1;;
+      *) fail "Unhandled $uname_s machine architecture: $uname_m" ;;
     esac
     ;;
   Windows_NT)
     OS=win32
-    case `uname -m` in
+    uname_m="`uname -m`"
+    case "$uname_m" in
       *86) ARCHITECTURE=intel32;;
-      *) exit 1;;
+      *) fail "Unhandled $uname_s machine architecture: $uname_m " ;;
     esac
     ;;
   CYGWIN_NT*)
@@ -105,16 +123,15 @@ case `uname -s` in
     else
        OS=win32
     fi
-    case `uname -m` in
+    uname_m="`uname -m`"
+    case "$uname_m" in
        *86) ARCHITECTURE=intel32;;
-       *) exit 1;;
+       *) fail "Unhandled $uname_s machine architecture: $uname_m " ;;
     esac
     ;;
-  *) exit 1;;
+  *) fail "Could not handle architecture: $uname_s" ;;
 esac
 
 echo "ARCHITECTURE=$ARCHITECTURE; OS=$OS"
 
 exit 0
-
-
