2013-01-03-20.52.13: Cloned all the gtk stuff to produce a zero-th order sdl infrastructure.

diff --git a/sh/make-install b/sh/make-install
--- a/sh/make-install
+++ b/sh/make-install
@@ -84,6 +84,14 @@ if [ -z "$DESTDIR" ] && [ -f /usr/bin/mythryl-gtk-server ]; then
     fi
 fi
 
+if [ -z "$DESTDIR" ] && [ -f /usr/bin/mythryl-sdl-server ]; then
+    mv /usr/bin/mythryl-sdl-server /usr/bin/mythryl-sdl-server.old
+    if [ -f /usr/bin/mythryl-sdl-server ]; then
+        echo "Couldn't rename /usr/bin/mythryl-sdl-server to /usr/bin/mythryl-sdl-server.old -- you may need to su to root to install."
+        exit 1
+    fi
+fi
+
 cp bin/mythryl-runtime-intel32 "$DESTDIR"/usr/bin/mythryl-runtime-intel32
 chmod 755                   "$DESTDIR"/usr/bin/mythryl-runtime-intel32
 if [ ! -x "$DESTDIR"/usr/bin/mythryl-runtime-intel32 ]; then
@@ -127,6 +135,11 @@ if [ -x bin/mythryl-gtk-server ]; then
     chmod 755        /usr/bin/mythryl-gtk-server
 fi
 
+if [ -x bin/mythryl-sdl-server ]; then
+    cp bin/mythryl-sdl-server /usr/bin/mythryl-sdl-server
+    chmod 755        /usr/bin/mythryl-sdl-server
+fi
+
 # Function to install a script.
 #   This takes care of patching the source
 #   of the script with the SHELL and BIN_DIR
@@ -151,6 +164,6 @@ patch_and_install_script _build-an-executable-mythryl-heap-image build-an-execut
 
 
 echo "Installed in $DESTDIR/usr/bin:"
-ls -l "$DESTDIR"/usr/bin/mythryl-runtime-intel32 "$DESTDIR"/usr/bin/mythryl-ld "$DESTDIR"/usr/bin/mythryl "$DESTDIR"/usr/bin/my "$DESTDIR"/usr/bin/mythryld "$DESTDIR"/usr/bin/mythryl-gtk-server "$DESTDIR"/usr/bin/build-an-executable-mythryl-heap-image
+ls -l "$DESTDIR"/usr/bin/mythryl-runtime-intel32 "$DESTDIR"/usr/bin/mythryl-ld "$DESTDIR"/usr/bin/mythryl "$DESTDIR"/usr/bin/my "$DESTDIR"/usr/bin/mythryld "$DESTDIR"/usr/bin/mythryl-gtk-server "$DESTDIR"/usr/bin/mythryl-sdl-server "$DESTDIR"/usr/bin/build-an-executable-mythryl-heap-image
 
 exit 0
diff --git a/sh/uninstall b/sh/uninstall
--- a/sh/uninstall
+++ b/sh/uninstall
@@ -71,6 +71,17 @@ if [ -x /usr/bin/mythryl-gtk-server ]; then
     fi
 fi
 
+if [ -x /usr/bin/mythryl-sdl-server ]; then
+    rm  /usr/bin/mythryl-sdl-server
+
+    if [ -x /usr/bin/mythryl-sdl-server ]; then
+	echo "Couldn't rm /usr/bin/mythryl-sdl-server -- you may need to su to root to uninstall."
+	exit 1
+    else
+	echo "/usr/bin/mythryl-sdl-server successfully removed."
+    fi
+fi
+
 if [ -x /usr/bin/build-an-executable-mythryl-heap-image ]; then
     rm  /usr/bin/build-an-executable-mythryl-heap-image
 
