2011-08-04-02.02.50: 4.0.0 release, try 3.

diff --git a/src/lib/c-glue-lib/build b/src/lib/c-glue-lib/build
--- a/src/lib/c-glue-lib/build
+++ b/src/lib/c-glue-lib/build
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Install-time build script for c.make6.
+# Install-time build script for c.lib.
 #
 # We will normally be run as a result of a toplevel "make rest".
 #
-# Our main result is the freezefile src/lib/c-glue-lib/c.make6.frozen.
+# Our main result is the freezefile src/lib/c-glue-lib/c.lib.frozen.
 
 bin/mythryld <<EOF
-    make7::freeze "src/lib/c-glue-lib/c.make6";
+    makelib::freeze "src/lib/c-glue-lib/c.lib";
 EOF
 
-if   [ -f "src/lib/c-glue-lib/c.make6.frozen" ]
+if [ -f "src/lib/c-glue-lib/c.lib.frozen" ]
 then
-     echo "                src/lib/c-glue-lib/build:   Successfully created src/lib/c-glue-lib/c.make6.frozen:"
-     echo "                src/lib/c-glue-lib/build:   `ls -l src/lib/c-glue-lib/c.make6.frozen`"
+    echo "                src/lib/c-glue-lib/build:   Successfully created    src/lib/c-glue-lib/c.lib.frozen:"
+    echo "                src/lib/c-glue-lib/build:                           `ls -l src/lib/c-glue-lib/c.lib.frozen`"
 else
-     echo "                src/lib/c-glue-lib/build:   Failed to create src/lib/c-glue-lib/c.make6.frozen"
-     exit 1
+    echo "                src/lib/c-glue-lib/build:   FAILED TO CREATE        src/lib/c-glue-lib/c.lib.frozen"
+    exit 1
 fi
 
 exit 0;
diff --git a/src/lib/c-glue-lib/internals/build b/src/lib/c-glue-lib/internals/build
--- a/src/lib/c-glue-lib/internals/build
+++ b/src/lib/c-glue-lib/internals/build
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Install-time build script for c-internals.make6.
+# Install-time build script for c-internals.lib.
 #
 # We will normally be run as a result of a toplevel "make rest".
 #
-# Our main result is the freezefile src/lib/c-glue-lib/internals/c-internals.make6.frozen.
+# Our main result is the freezefile src/lib/c-glue-lib/internals/c-internals.lib.frozen.
 
 bin/mythryld <<EOF
-    make7::freeze "src/lib/c-glue-lib/internals/c-internals.make6";
+    makelib::freeze "src/lib/c-glue-lib/internals/c-internals.lib";
 EOF
 
-if   [ -f "src/lib/c-glue-lib/internals/c-internals.make6.frozen" ]
+if [ -f "src/lib/c-glue-lib/internals/c-internals.lib.frozen" ]
 then
-     echo "      src/lib/c-glue-lib/internals/build:   Successfully created src/lib/c-glue-lib/internals/c-internals.make6.frozen:"
-     echo "      src/lib/c-glue-lib/internals/build:   `ls -l src/lib/c-glue-lib/internals/c-internals.make6.frozen`"
+    echo "      src/lib/c-glue-lib/internals/build:   Successfully created    src/lib/c-glue-lib/internals/c-internals.lib.frozen:"
+    echo "      src/lib/c-glue-lib/internals/build:                           `ls -l src/lib/c-glue-lib/internals/c-internals.lib.frozen`"
 else
-     echo "      src/lib/c-glue-lib/internals/build:   Failed to create src/lib/c-glue-lib/internals/c-internals.make6.frozen"
-     exit 1
+    echo "      src/lib/c-glue-lib/internals/build:   FAILED TO CREATE        src/lib/c-glue-lib/internals/c-internals.lib.frozen"
+    exit 1
 fi
 
 exit 0;
diff --git a/src/lib/c-kit/src/build b/src/lib/c-kit/src/build
--- a/src/lib/c-kit/src/build
+++ b/src/lib/c-kit/src/build
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Install-time build script for c-kit-lib.make6.
+# Install-time build script for c-kit.lib.
 #
 # We will normally be run as a result of a toplevel "make rest".
 #
-# Our main result is the freezefile src/lib/c-kit/src/c-kit-lib.make6.frozen.
+# Our main result is the freezefile src/lib/c-kit/src/c-kit.lib.frozen.
 
 bin/mythryld <<EOF
-    make7::freeze "src/lib/c-kit/src/c-kit-lib.make6";
+    makelib::freeze "src/lib/c-kit/src/c-kit.lib";
 EOF
 
-if   [ -f "src/lib/c-kit/src/c-kit-lib.make6.frozen" ]
+if [ -f "src/lib/c-kit/src/c-kit.lib.frozen" ]
 then
-     echo "                 src/lib/c-kit/src/build:   Successfully created src/lib/c-kit/src/c-kit-lib.make6.frozen:"
-     echo "                 src/lib/c-kit/src/build:   `ls -l src/lib/c-kit/src/c-kit-lib.make6.frozen`"
+    echo "                 src/lib/c-kit/src/build:   Successfully created    src/lib/c-kit/src/c-kit.lib.frozen:"
+    echo "                 src/lib/c-kit/src/build:                           `ls -l src/lib/c-kit/src/c-kit.lib.frozen`"
 else
-     echo "                 src/lib/c-kit/src/build:   Failed to create src/lib/c-kit/src/c-kit-lib.make6.frozen"
-     exit 1
+    echo "                 src/lib/c-kit/src/build:   FAILED TO CREATE        src/lib/c-kit/src/c-kit.lib.frozen"
+    exit 1
 fi
 
 exit 0;
diff --git a/src/lib/regex/build b/src/lib/regex/build
--- a/src/lib/regex/build
+++ b/src/lib/regex/build
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Install-time build script for regex-lib.make6. THIS SHOULD BE OBSOLETE SINCE regex-lib.make6 got merged into lib7.make6
+# Install-time build script for regex-lib.lib. THIS SHOULD BE OBSOLETE SINCE regex-lib.lib got merged into lib7.lib
 #
 # We will normally be run as a result of a toplevel "make rest".
 #
-# Our main result is the freezefile src/lib/regex/regex-lib.make6.frozen.
+# Our main result is the freezefile src/lib/regex/regex-lib.lib.frozen.
 
 bin/mythryld <<EOF
-    make7::freeze "src/lib/regex/regex-lib.make6";
+    makelib::freeze "src/lib/regex/regex-lib.lib";
 EOF
 
-if   [ -f "src/lib/regex/regex-lib.make6.frozen" ]
+if [ -f "src/lib/regex/regex-lib.lib.frozen" ]
 then
-     echo "                     src/lib/regex/build:   Successfully created src/lib/regex/regex-lib.make6.frozen:"
-     echo "                     src/lib/regex/build:   `ls -l src/lib/regex/regex-lib.make6.frozen`"
+    echo "                     src/lib/regex/build:   Successfully created    src/lib/regex/regex-lib.lib.frozen:"
+    echo "                     src/lib/regex/build:                           `ls -l src/lib/regex/regex-lib.lib.frozen`"
 else
-     echo "                     src/lib/regex/build:   Failed to create src/lib/regex/regex-lib.make6.frozen"
-     exit 1
+    echo "                     src/lib/regex/build:   FAILED TO CREATE        src/lib/regex/regex-lib.lib.frozen"
+    exit 1
 fi
 
 exit 0;
diff --git a/src/lib/x-kit/tut/badbricks-game/build-badbricks-game-app b/src/lib/x-kit/tut/badbricks-game/build-badbricks-game-app
--- a/src/lib/x-kit/tut/badbricks-game/build-badbricks-game-app
+++ b/src/lib/x-kit/tut/badbricks-game/build-badbricks-game-app
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Install-time build script for bricks-app.make6.
+# Install-time build script for bricks-app.lib.
 #
 # We will normally be run as a result of a toplevel "make rest".
 #
-# Our main result is the freezefile src/lib/x-kit/tut/badbricks-game/badbricks-game-app.make6.frozen.
+# Our main result is the freezefile src/lib/x-kit/tut/badbricks-game/badbricks-game-app.lib.frozen.
 
 bin/mythryld <<EOF
-    make7::freeze "src/lib/x-kit/tut/badbricks-game/badbricks-game-app.make6";
+    makelib::freeze "src/lib/x-kit/tut/badbricks-game/badbricks-game-app.lib";
 EOF
 
-if   [ -f "src/lib/x-kit/tut/badbricks-game/badbricks-game-app.make6.frozen" ]
+if   [ -f "src/lib/x-kit/tut/badbricks-game/badbricks-game-app.lib.frozen" ]
 then
-     echo "            build-badbricks-game-app:   Successfully created: src/lib/x-kit/tut/badbricks-game/badbricks-game-app.make6.frozen"
-     echo "            build-badbricks-game-app:   `ls -l src/lib/x-kit/tut/badbricks-game/badbricks-game-app.make6.frozen`"
+    echo "                build-badbricks-game-app:   Successfully created    src/lib/x-kit/tut/badbricks-game/badbricks-game-app.lib.frozen:"
+    echo "                build-badbricks-game-app:                           `ls -l src/lib/x-kit/tut/badbricks-game/badbricks-game-app.lib.frozen`"
 else
-     echo "            build-badbricks-game-app:   Failed to create src/lib/x-kit/tut/badbricks-game/badbricks-game-app.make6.frozen"
-     exit 1
+    echo "                build-badbricks-game-app:   FAILED TO CREATE        src/lib/x-kit/tut/badbricks-game/badbricks-game-app.lib.frozen"
+    exit 1
 fi
 
 exit 0;
diff --git a/src/lib/x-kit/tut/basicwin/build-basicwin-app b/src/lib/x-kit/tut/basicwin/build-basicwin-app
--- a/src/lib/x-kit/tut/basicwin/build-basicwin-app
+++ b/src/lib/x-kit/tut/basicwin/build-basicwin-app
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Install-time build script for basicwin-app.make6.
+# Install-time build script for basicwin-app.lib.
 #
 # We will normally be run as a result of a toplevel "make rest".
 #
-# Our main result is the freezefile src/lib/x-kit/tut/basicwin/basicwin-app.make6.frozen.
+# Our main result is the freezefile src/lib/x-kit/tut/basicwin/basicwin-app.lib.frozen.
 
 bin/mythryld <<EOF
-    make7::freeze "src/lib/x-kit/tut/basicwin/basicwin-app.make6";
+    makelib::freeze "src/lib/x-kit/tut/basicwin/basicwin-app.lib";
 EOF
 
-if   [ -f "src/lib/x-kit/tut/basicwin/basicwin-app.make6.frozen" ]
+if   [ -f "src/lib/x-kit/tut/basicwin/basicwin-app.lib.frozen" ]
 then
-     echo " .../example/basicwin/build-basicwin-app:   Successfully created: src/lib/x-kit/tut/basicwin/basicwin-app.make6.frozen"
-     echo " .../example/basicwin/build-basicwin-app:   `ls -l src/lib/x-kit/tut/basicwin/basicwin-app.make6.frozen`"
+    echo "                      build-basicwin-app:   Successfully created    src/lib/x-kit/tut/basicwin/basicwin-app.lib.frozen:"
+    echo "                      build-basicwin-app:                           `ls -l src/lib/x-kit/tut/basicwin/basicwin-app.lib.frozen`"
 else
-     echo " .../example/basicwin/build-basicwin-app:   Failed to create src/lib/x-kit/tut/basicwin/basicwin-app.make6.frozen"
-     exit 1
+    echo "                      build-basicwin-app:   FAILED TO CREATE        src/lib/x-kit/tut/basicwin/basicwin-app.lib.frozen"
+    exit 1
 fi
 
 exit 0;
diff --git a/src/lib/x-kit/tut/bitmap-editor/build-bitmap-editor b/src/lib/x-kit/tut/bitmap-editor/build-bitmap-editor
--- a/src/lib/x-kit/tut/bitmap-editor/build-bitmap-editor
+++ b/src/lib/x-kit/tut/bitmap-editor/build-bitmap-editor
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Install-time build script for bitmap-editor.make6.
+# Install-time build script for bitmap-editor.lib.
 #
 # We will normally be run as a result of a toplevel "make rest".
 #
-# Our main result is the freezefile src/lib/x-kit/tut/bitmap-editor/bitmap-editor.make6.frozen.
+# Our main result is the freezefile src/lib/x-kit/tut/bitmap-editor/bitmap-editor.lib.frozen.
 
 bin/mythryld <<EOF
-    make7::freeze "src/lib/x-kit/tut/bitmap-editor/bitmap-editor.make6";
+    makelib::freeze "src/lib/x-kit/tut/bitmap-editor/bitmap-editor.lib";
 EOF
 
-if   [ -f "src/lib/x-kit/tut/bitmap-editor/bitmap-editor.make6.frozen" ]
+if   [ -f "src/lib/x-kit/tut/bitmap-editor/bitmap-editor.lib.frozen" ]
 then
-     echo "       bitmap-editor/build-bitmap-editor:   Successfully created: src/lib/x-kit/tut/bitmap-editor/bitmap-editor.make6.frozen"
-     echo "       bitmap-editor/build-bitmap-editor:   `ls -l src/lib/x-kit/tut/bitmap-editor/bitmap-editor.make6.frozen`"
+    echo "                     build-bitmap-editor:   Successfully created    src/lib/x-kit/tut/bitmap-editor/bitmap-editor.lib.frozen:"
+    echo "                     build-bitmap-editor:                           `ls -l src/lib/x-kit/tut/bitmap-editor/bitmap-editor.lib.frozen`"
 else
-     echo "       bitmap-editor/build-bitmap-editor:   Failed to create src/lib/x-kit/tut/bitmap-editor/bitmap-editor.make6.frozen"
-     exit 1
+    echo "                     build-bitmap-editor:   FAILED TO CREATE        src/lib/x-kit/tut/bitmap-editor/bitmap-editor.lib.frozen"
+    exit 1
 fi
 
 exit 0;
diff --git a/src/lib/x-kit/tut/bouncing-heads/build-bouncing-heads-app b/src/lib/x-kit/tut/bouncing-heads/build-bouncing-heads-app
--- a/src/lib/x-kit/tut/bouncing-heads/build-bouncing-heads-app
+++ b/src/lib/x-kit/tut/bouncing-heads/build-bouncing-heads-app
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Install-time build script for bouncing-heads-app.make6.
+# Install-time build script for bouncing-heads-app.lib.
 #
 # We will normally be run as a result of a toplevel "make rest".
 #
-# Our main result is the freezefile src/lib/x-kit/tut/bounce/bouncing-heads-app.make6.frozen.
+# Our main result is the freezefile src/lib/x-kit/tut/bounce/bouncing-heads-app.lib.frozen.
 
 bin/mythryld <<EOF
-    make7::freeze "src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.make6";
+    makelib::freeze "src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.lib";
 EOF
 
-if   [ -f "src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.make6.frozen" ]
+if [ -f "src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.lib.frozen" ]
 then
-     echo "            build-bouncing-heads-app:   Successfully created: src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.make6.frozen"
-     echo "            build-bouncing-heads-app:   `ls -l src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.make6.frozen`"
+    echo "                build-bouncing-heads-app:   Successfully created    src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.lib.frozen:"
+    echo "                build-bouncing-heads-app:                           `ls -l src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.lib.frozen`"
 else
-     echo "            build-bouncing-heads-app:   Failed to create src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.make6.frozen"
-     exit 1
+    echo "                build-bouncing-heads-app:   FAILED TO CREATE        src/lib/x-kit/tut/bouncing-heads/bouncing-heads-app.lib.frozen"
+    exit 1
 fi
 
 exit 0;
diff --git a/src/lib/x-kit/tut/calculator/build-calculator-app b/src/lib/x-kit/tut/calculator/build-calculator-app
--- a/src/lib/x-kit/tut/calculator/build-calculator-app
+++ b/src/lib/x-kit/tut/calculator/build-calculator-app
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Install-time build script for calc-app.make6.
+# Install-time build script for calc-app.lib.
 #
 # We will normally be run as a result of a toplevel "make rest".
 #
-# Our main result is the freezefile src/lib/x-kit/tut/calculator/calculator-app.make6.frozen.
+# Our main result is the freezefile src/lib/x-kit/tut/calculator/calculator-app.lib.frozen.
 
 bin/mythryld <<EOF
-    make7::freeze "src/lib/x-kit/tut/calculator/calculator-app.make6";
+    makelib::freeze "src/lib/x-kit/tut/calculator/calculator-app.lib";
 EOF
 
-if   [ -f "src/lib/x-kit/tut/calculator/calculator-app.make6.frozen" ]
+if [ -f "src/lib/x-kit/tut/calculator/calculator-app.lib.frozen" ]
 then
-     echo " x-kit/tut/calculator/build-calc-app:   Successfully created: src/lib/x-kit/tut/calculator/calculator-app.make6.frozen"
-     echo " x-kit/tut/calculator/build-calc-app:   `ls -l src/lib/x-kit/tut/calculator/calculator-app.make6.frozen`"
+    echo "                    build-calculator-app:   Successfully created    src/lib/x-kit/tut/calculator/calculator-app.lib.frozen:"
+    echo "                    build-calculator-app:                           `ls -l src/lib/x-kit/tut/calculator/calculator-app.lib.frozen`"
 else
-     echo " x-kit/tut/calculator/build-calc-app:   Failed to create src/lib/x-kit/tut/calculator/calculator-app.make6.frozen"
-     exit 1
+    echo "                    build-calculator-app:   FAILED TO CREATE        src/lib/x-kit/tut/calculator/calculator-app.lib.frozen"
+    exit 1
 fi
 
 exit 0;
diff --git a/src/lib/x-kit/tut/nbody/build-nbody-app b/src/lib/x-kit/tut/nbody/build-nbody-app
--- a/src/lib/x-kit/tut/nbody/build-nbody-app
+++ b/src/lib/x-kit/tut/nbody/build-nbody-app
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Install-time build script for nbody-app.make6.
+# Install-time build script for nbody-app.lib.
 #
 # We will normally be run as a result of a toplevel "make rest".
 #
-# Our main result is the freezefile src/lib/x-kit/tut/nbody/nbody-app.make6.frozen.
+# Our main result is the freezefile src/lib/x-kit/tut/nbody/nbody-app.lib.frozen.
 
 bin/mythryld <<EOF
-    make7::freeze "src/lib/x-kit/tut/nbody/nbody-app.make6";
+    makelib::freeze "src/lib/x-kit/tut/nbody/nbody-app.lib";
 EOF
 
-if   [ -f "src/lib/x-kit/tut/nbody/nbody-app.make6.frozen" ]
+if [ -f "src/lib/x-kit/tut/nbody/nbody-app.lib.frozen" ]
 then
-     echo " lib/x-kit/tut/nbody/build-nbody-app:   Successfully created: src/lib/x-kit/tut/nbody/nbody-app.make6.frozen"
-     echo " lib/x-kit/tut/nbody/build-nbody-app:   `ls -l src/lib/x-kit/tut/nbody/nbody-app.make6.frozen`"
+    echo "                         build-nbody-app:   Successfully created    src/lib/x-kit/tut/nbody/nbody-app.lib.frozen:"
+    echo "                         build-nbody-app:                           `ls -l src/lib/x-kit/tut/nbody/nbody-app.lib.frozen`"
 else
-     echo " lib/x-kit/tut/nbody/build-nbody-app:   Failed to create src/lib/x-kit/tut/nbody/nbody-app.make6.frozen"
-     exit 1
+    echo "                         build-nbody-app:   FAILED TO CREATE        src/lib/x-kit/tut/nbody/nbody-app.lib.frozen"
+    exit 1
 fi
 
 exit 0;
diff --git a/src/lib/x-kit/tut/plaid/build-plaid-app b/src/lib/x-kit/tut/plaid/build-plaid-app
--- a/src/lib/x-kit/tut/plaid/build-plaid-app
+++ b/src/lib/x-kit/tut/plaid/build-plaid-app
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Install-time build script for plaid-app.make6.
+# Install-time build script for plaid-app.lib.
 #
 # We will normally be run as a result of a toplevel "make rest".
 #
-# Our main result is the freezefile src/lib/x-kit/tut/plaid/plaid-app.make6.frozen.
+# Our main result is the freezefile src/lib/x-kit/tut/plaid/plaid-app.lib.frozen.
 
 bin/mythryld <<EOF
-    make7::freeze "src/lib/x-kit/tut/plaid/plaid-app.make6";
+    makelib::freeze "src/lib/x-kit/tut/plaid/plaid-app.lib";
 EOF
 
-if   [ -f "src/lib/x-kit/tut/plaid/plaid-app.make6.frozen" ]
+if [ -f "src/lib/x-kit/tut/plaid/plaid-app.lib.frozen" ]
 then
-     echo " lib/x-kit/tut/plaid/build-plaid-app:   Successfully created: src/lib/x-kit/tut/plaid/plaid-app.make6.frozen"
-     echo " lib/x-kit/tut/plaid/build-plaid-app:   `ls -l src/lib/x-kit/tut/plaid/plaid-app.make6.frozen`"
+    echo "                         build-plaid-app:   Successfully created    src/lib/x-kit/tut/plaid/plaid-app.lib.frozen:"
+    echo "                         build-plaid-app:                           `ls -l src/lib/x-kit/tut/plaid/plaid-app.lib.frozen`"
 else
-     echo " lib/x-kit/tut/plaid/build-plaid-app:   Failed to create src/lib/x-kit/tut/plaid/plaid-app.make6.frozen"
-     exit 1
+    echo "                         build-plaid-app:   Failed to create src/lib/x-kit/tut/plaid/plaid-app.lib.frozen"
+    exit 1
 fi
 
 exit 0;
diff --git a/src/lib/x-kit/tut/show-graph/build-show-graph-app b/src/lib/x-kit/tut/show-graph/build-show-graph-app
--- a/src/lib/x-kit/tut/show-graph/build-show-graph-app
+++ b/src/lib/x-kit/tut/show-graph/build-show-graph-app
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Install-time build script for show-graph-app.make6.
+# Install-time build script for show-graph-app.lib.
 #
 # We will normally be run as a result of a toplevel "make rest".
 #
-# Our main result is the freezefile src/lib/x-kit/tut/show-graph/show-graph-app.make6.frozen.
+# Our main result is the freezefile src/lib/x-kit/tut/show-graph/show-graph-app.lib.frozen.
 
 bin/mythryld <<EOF
-    make7::freeze "src/lib/x-kit/tut/show-graph/show-graph-app.make6";
+    makelib::freeze "src/lib/x-kit/tut/show-graph/show-graph-app.lib";
 EOF
 
-if   [ -f "src/lib/x-kit/tut/show-graph/show-graph-app.make6.frozen" ]
+if [ -f "src/lib/x-kit/tut/show-graph/show-graph-app.lib.frozen" ]
 then
-     echo " tut/show-graph/build-show-graph-app:   Successfully created: src/lib/x-kit/tut/show-graph/show-graph-app.make6.frozen"
-     echo " tut/show-graph/build-show-graph-app:   `ls -l src/lib/x-kit/tut/show-graph/show-graph-app.make6.frozen`"
+    echo "                    build-show-graph-app:   Successfully created    src/lib/x-kit/tut/show-graph/show-graph-app.lib.frozen:"
+    echo "                    build-show-graph-app:                           `ls -l src/lib/x-kit/tut/show-graph/show-graph-app.lib.frozen`"
 else
-     echo " tut/show-graph/build-show-graph-app:   Failed to create src/lib/x-kit/tut/show-graph/show-graph-app.make6.frozen"
-     exit 1
+    echo "                    build-show-graph-app:   FAILED TO CREATE        src/lib/x-kit/tut/show-graph/show-graph-app.lib.frozen"
+    exit 1
 fi
 
 exit 0;
diff --git a/src/lib/x-kit/tut/triangle/build-triangle-app b/src/lib/x-kit/tut/triangle/build-triangle-app
--- a/src/lib/x-kit/tut/triangle/build-triangle-app
+++ b/src/lib/x-kit/tut/triangle/build-triangle-app
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Install-time build script for triangle-app.make6.
+# Install-time build script for triangle-app.lib.
 #
 # We will normally be run as a result of a toplevel "make rest".
 #
-# Our main result is the freezefile src/lib/x-kit/tut/triangle/triangle-app.make6.frozen.
+# Our main result is the freezefile src/lib/x-kit/tut/triangle/triangle-app.lib.frozen.
 
 bin/mythryld <<EOF
-    make7::freeze "src/lib/x-kit/tut/triangle/triangle-app.make6";
+    makelib::freeze "src/lib/x-kit/tut/triangle/triangle-app.lib";
 EOF
 
-if   [ -f "src/lib/x-kit/tut/triangle/triangle-app.make6.frozen" ]
+if [ -f "src/lib/x-kit/tut/triangle/triangle-app.lib.frozen" ]
 then
-     echo "     tut/triangle/build-triangle-app:   Successfully created: src/lib/x-kit/tut/triangle/triangle-app.make6.frozen"
-     echo "     tut/triangle/build-triangle-app:   `ls -l src/lib/x-kit/tut/triangle/triangle-app.make6.frozen`"
+    echo "                      build-triangle-app:   Successfully created    src/lib/x-kit/tut/triangle/triangle-app.lib.frozen:"
+    echo "                      build-triangle-app:                           `ls -l src/lib/x-kit/tut/triangle/triangle-app.lib.frozen`"
 else
-     echo "     tut/triangle/build-triangle-app:   Failed to create src/lib/x-kit/tut/triangle/triangle-app.make6.frozen"
-     exit 1
+    echo "                      build-triangle-app:   FAILED TO CREATE        src/lib/x-kit/tut/triangle/triangle-app.lib.frozen"
+    exit 1
 fi
 
 exit 0;
diff --git a/src/lib/x-kit/tut/widget/build-widgets b/src/lib/x-kit/tut/widget/build-widgets
--- a/src/lib/x-kit/tut/widget/build-widgets
+++ b/src/lib/x-kit/tut/widget/build-widgets
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Install-time build script for widgets.make6.
+# Install-time build script for widgets.lib.
 #
 # We will normally be run as a result of a toplevel "make rest".
 #
-# Our main result is the freezefile src/lib/x-kit/tut/widget/widgets.make6.frozen.
+# Our main result is the freezefile src/lib/x-kit/tut/widget/widgets.lib.frozen.
 
 bin/mythryld <<EOF
-    make7::freeze "src/lib/x-kit/tut/widget/widgets.make6";
+    makelib::freeze "src/lib/x-kit/tut/widget/widgets.lib";
 EOF
 
-if   [ -f "src/lib/x-kit/tut/widget/widgets.make6.frozen" ]
+if [ -f "src/lib/x-kit/tut/widget/widgets.lib.frozen" ]
 then
-     echo "  lib/x-kit/tut/widget/build-widgets:   Successfully created: src/lib/x-kit/tut/widget/widgets.make6.frozen"
-     echo "  lib/x-kit/tut/widget/build-widgets:   `ls -l src/lib/x-kit/tut/widget/widgets.make6.frozen`"
+    echo "                           build-widgets:   Successfully created    src/lib/x-kit/tut/widget/widgets.lib.frozen:"
+    echo "                           build-widgets:                           `ls -l src/lib/x-kit/tut/widget/widgets.lib.frozen`"
 else
-     echo "  lib/x-kit/tut/widget/build-widgets:   Failed to create src/lib/x-kit/tut/widget/widgets.make6.frozen"
-     exit 1
+    echo "                           build-widgets:   Failed to create src/lib/x-kit/tut/widget/widgets.lib.frozen"
+    exit 1
 fi
 
 exit 0;
